version: 2.1

jobs:
  lint:
    machine: true
    steps:
      - checkout
      - run: ./bin/lint
  publish:
    type: release
    machine: true
    steps:
      - checkout
      - run: VERSION=$CIRCLE_BUILD_NUM ./bin/publish

workflows:
  check-build-and-deploy:
    jobs:
      - lint
      - publish:
          requires:
            - lint
          filters:
            branches:
              only: main