version: 2.1

jobs:
  lint:
    machine: true
    steps:
      - checkout
      - run: ./bin/lint
  publish:
    machine: true
    steps:
      - checkout
      - run: VERSION=$CIRCLE_BUILD_NUM ./bin/publish
  test-nvim-install-via-apk:
    machine: true
    steps:
      - checkout
      - run: ./bin/test-apk-install
  test-nvim-install-via-brew:
    machine: true
    steps:
      - checkout
      - run: ./bin/test-brew-install
  test-nvim-install-via-apt:
    machine: true
    steps:
      - checkout
      - run: ./bin/test-apt-install

workflows:
  check-build-and-deploy:
    jobs:
      - lint
      - test-nvim-install-via-apk
      - test-nvim-install-via-brew
      - test-nvim-install-via-apt
      - publish:
          requires:
            - lint
            - test-nvim-install-via-apk
            - test-nvim-install-via-brew
            - test-nvim-install-via-apt
          filters:
            branches:
              only: main